Added missing comma in setup.py
Fixes this error:

c:\pyFASST-0.9.2\pyfasst\SeparateLeadStereo>python setup.py build_ext --inplace
  File "setup.py", line 7
    license='',
          ^
SyntaxError: invalid syntax